# Generated by Django 4.0.6 on 2022-07-14 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image_post', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagestore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagesave',
            name='image_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_post.imagestore'),
        ),
        migrations.AddField(
            model_name='imagesave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagelike',
            name='image_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image_post.imagestore'),
        ),
        migrations.AddField(
            model_name='imagelike',
            name='like_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imagelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
